### ISSUE TITLE
AttributeError: 'RedisChannelLayer' object has no attribute 'ChannelFull'

### ISSUE THREAD

**Issue by vladimirnani** [andrewgodwin/asgi_redis#5]
I am using web sockets with **RedisChannelLayer**. Frequently get following error:
```
: Traceback (most recent call last): 
May 19 11:19:14  app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger 
May 19 11:19:14  app/web.1:     return callWithContext({"system": lp}, func, *args, **kw) 
May 19 11:19:14  app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext 
May 19 11:19:14  app/web.1:     return context.call({ILogContext: newCtx}, func, *args, **kw) 
May 19 11:19:14  app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext 
May 19 11:19:14  app/web.1:     return self.currentContext().callWithContext(ctx, func, *args, **kw) 
May 19 11:19:14  app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext 
May 19 11:19:14  app/web.1:     return func(*args,**kw) 
May 19 11:19:14  app/web.1: --- <exception caught here> --- 
May 19 11:19:14  app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite 
May 19 11:19:14  app/web.1:     why = selectable.doRead() 
May 19 11:19:14  app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/tcp.py", line 209, in doRead 
May 19 11:19:14  app/web.1:     return self._dataReceived(data) 
May 19 11:19:14  app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived 
May 19 11:19:14  app/web.1:     rval = self.protocol.dataReceived(data) 
May 19 11:19:14  app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived 
May 19 11:19:14  app/web.1:     why = self.lineReceived(line) 
May 19 11:19:14  app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/web/http.py", line 1688, in lineReceived 
May 19 11:19:14  app/web.1:     self.allContentReceived() 
May 19 11:19:14  app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/web/http.py", line 1767, in allContentReceived 
May 19 11:19:14  app/web.1:     req.requestReceived(command, path, version) 
May 19 11:19:14  app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/web/http.py", line 768, in requestReceived 
May 19 11:19:14  app/web.1:     self.process() 
May 19 11:19:14  app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/daphne/http_protocol.py", line 128, in process 
May 19 11:19:14  app/web.1:     except self.factory.channel_layer.ChannelFull: 
May 19 11:19:14  app/web.1: exceptions.AttributeError: 'RedisChannelLayer' object has no attribute 'ChannelFull' 
```
As i understand `RedisChannelLayer(object)` base class is `object` but it expects to be of type  [`BaseChannelLayer`](https://github.com/andrewgodwin/asgiref/blob/master/asgiref/base_layer.py) in daphne [`http_protocol.py`](https://github.com/andrewgodwin/daphne/blob/master/daphne/http_protocol.py). 
Or it is just incompatible with django channels and im using it wrong. Thanks.

**Comment by vladimirnani** [comment]
Oops. I had outdated version. Thanks anyway. :)

**Comment by jacksonmj24** [comment]
Could you please output your Version. I.e channel and redis
